records = {
    [3773] = {name='Besieged Participation (M)',parent='Other',category='Monthly Objectives',},
    [3774] = {name='Campaign Participation (M)',parent='Other',category='Monthly Objectives',},
    [3000] = {name='Unity Communique A (UC)',parent='Unity', category='Unity (Shared A)',},
    [3001] = {name='Home Point Comrade A (UC)',parent='Unity', category='Unity (Shared A)',},
    [3002] = {name='Vanquish Multiple Enemies  A (UC)',parent='Unity', category='Unity (Shared A)',},
    [3055] = {name='Van. Enemies w. Unity Leader A (UC)',parent='Unity', category='Unity (Shared A)',},
    [3009] = {name='Unity Communique B (UC)',parent='Unity', category='Unity (Shared B)',},
    [3011] = {name='Vanquish Multiple Enemies B (UC)',parent='Unity', category='Unity (Shared B)',},
    [3056] = {name='Van. Enemies w. Unity Leader B (UC)',parent='Unity', category='Unity (Shared B)',},
    [3018] = {name='Unity Communique C (UC)',parent='Unity', category='Unity (Shared C)',},
    [3019] = {name='Home Point Comrade C (UC)',parent='Unity', category='Unity (Shared C)',},
    [3020] = {name='Vanquish Multiple Enemies C (UC)',parent='Unity', category='Unity (Shared C)',},
    [3057] = {name='Van. Enemies w. Unity Leader C (UC)',parent='Unity', category='Unity (Shared C)',},
    [3027] = {name='Unity Communique D (UC)',parent='Unity', category='Unity (Shared D)',},
    [3029] = {name='Vanquish Multiple Enemies D (UC)',parent='Unity', category='Unity (Shared D)',},
    [3058] = {name='Van. Enemies w. Unity Leader D (UC)',parent='Unity', category='Unity (Shared D)',},
    [3036] = {name='Unity Communique E (UC)',parent='Unity', category='Unity (Shared E)',},
    [3037] = {name='Home Point Comrade E (UC)',parent='Unity', category='Unity (Shared E)',},
    [3038] = {name='Vanquish Multiple Enemies E (UC)',parent='Unity', category='Unity (Shared E)',},
    [3059] = {name='Van. Enemies w. Unity Leader E (UC)',parent='Unity', category='Unity (Shared E)',},
    [3045] = {name='Unity Communique F (UC)',parent='Unity', category='Unity (Shared F)',},
    [3047] = {name='Vanquish Multiple Enemies F (UC)',parent='Unity', category='Unity (Shared F)',},
    [3060] = {name='Van. Enemies w. Unity Leader F (UC)',parent='Unity', category='Unity (Shared F)',},
    [3363] = {name='Gastro-revolution (W)',parent='Vana\'versary',shorts={'gastro1','grape'},},   -- eggs/grape
    [3371] = {name='Gastro-revolution 2 (W)',parent='Vana\'versary',shorts={'gastro2','apple'},}, -- apple pie
    [3381] = {name='Gastro-Revolution 3 (W)',parent='Vana\'versary',shorts={'gastro3','shroom',},}, -- roast mushroom
    [3390] = {name='Gastro-Revolution 4 (W)',parent='Vana\'versary',shorts={'gastro4','ginger',},}, -- ginger cookies
    [3367] = {name='Signet, brb (W)',parent='15th Vana\'versary I',shorts={'signet'},},
    [3374] = {name='Colorless (W)',parent='Vana\'versary',shorts={'tele','xtal',},},           -- telepoint xtal
    [3380] = {name='Sit (W)',parent='Vana\'versary',shorts={'sit',},},
    [3393] = {name='Auction House Blues (W)',parent='Vana\'versary',shorts={'besiegedw',},}, -- besieged
}

-- id to name mapping
roe_id_keys = {
    -- 'Basics'
    [] = 'First Step Forward',
    [] = 'All for One',
    [] = 'Vanquish One Enemy',
    [] = 'Undertake a FoV Training Regime',
    [] = 'Heal Without Using Magic',
    [11] = 'Undertake a GoV Training Regime',
    [] = 'Stepping into an Ambuscade',
    [] = 'Call Forth an Alter Ego',
    [] = 'Alter Ego: Valaineral',
    [] = 'Alter Ego: Mihli Aliapoh',
    [] = 'Alter Ego: Tenzen',
    [] = 'Alter Ego: Adelheid',
    [] = 'Alter Ego: Joachim',
    [1447] = 'Exploring the Trove',
    [1448] = 'Assist Channel',
    -- 'Intermediate'
    [1045] = 'Achieve Level 99',
    [] = 'An Eminent Scholar',
    [] = 'An Eminent Scholar 2',
    [] = 'An Eminent Scholar 3',
    [] = 'Always Stand on 117',
    [] = 'Taming the Wilds',
    [] = 'Skirmisher: Rala Waterways',
    [] = 'Skirmisher: Cirdas Caverns',
    [] = 'Skirmisher: Yorcia Weald',
    [] = 'Repelling an Ambuscade',
    [] = 'Artifact Reforger',
    [] = 'Artifact Reforger 2',
    [] = 'A. Skirmisher: Rala Waterways',
    [] = 'A. Skirmisher: Cirdas Caverns',
    [] = 'A. Skirmisher: Yorcia Weald',
    -- 'Synthesis'
    [100] = 'Speak to Carpenters\' Guild Master',
    [101] = 'Speak to Blacksmiths\' Guild Master',
    [102] = 'Speak to Goldsmiths\' Guild Master',
    [103] = 'Speak to Weavers\' Guild Master',
    [104] = 'Speak to Tanners\' Guild Master',
    [105] = 'Speak to Boneworkers\' Guild Master',
    [106] = 'Speak to Alchemists\' Guild Master',
    [] = 'Speak to Culinarians\' Guild Master',
    [] = 'Woodworking: Padded Box',
    [] = 'Smithing: Bronze Knife',
    [] = 'Goldsmithing: Copper Ring',
    [111] = 'Weaving: Headgear',
    [] = 'Tanning: Leather Bandana',
    [113] = 'Boneworking: Shell Powder',
    [] = 'Alchemy: Black Ink',
    [115] = 'Cooking: Pebble Soup',
    -- 'Quests 1'
    [] = 'Mog House Exit: San d\'Oria',
    [] = 'Mog House Exit: Bastok',
    [] = 'Mog House Exit: Windurst',
    [503] = 'Mog House Exit: Jeuno',
    [504] = 'Mog House Exit: Aht Urhgan',
    [505] = 'Obtain a Support Job',
    [506] = 'Obtain an Alter Ego: San d\'Oria',
    [507] = 'Obtain an Alter Ego: Bastok',
    [508] = 'Obtain an Alter Ego: Windurst',
    [509] = 'Obtain a Chocobo License',
    [510] = 'Obtain Job: Paladin',
    [511] = 'Obtain Job: Dark Knight',
    [512] = 'Obtain Job: Beastmaster',
    [513] = 'Obtain Job: Bard',
    [514] = 'Obtain Job: Ranger',
    [515] = 'Obtain Job: Samurai',
    [516] = 'Obtain Job: Ninja',
    [517] = 'Obtain Job:Dragoon',
    [518] = 'Obtain Job: Summoner',
    [519] = 'Obtain Job: Blue Mage',
    [520] = 'Obtain Job: Corsair',
    [521] = 'Obtain Job: Puppetmaster',
    [522] = 'Obtain Job: Dancer',
    [523] = 'Obtain Job: Scholar',
    [524] = 'Obtain Job: Geomancer',
    [525] = 'Obtain Job: Rune Fencer',
    -- 'Quests (Artifact 1)'
    [629] = 'WAR Artifact Quest I',
    [630] = 'WAR Artifact Quest II',
    [631] = 'WAR Artifact Quest III',
    [632] = 'MNK Artifact Quest I',
    [633] = 'MNK Artifact Quest II',
    [634] = 'MNK Artifact Quest III',
    [635] = 'WHM Artifact Quest I',
    [636] = 'WHM Artifact Quest II',
    [637] = 'WHM Artifact Quest III',
    [638] = 'BLM Artifact Quest I',
    [639] = 'BLM Artifact Quest II',
    [640] = 'BLM Artifact Quest III',
    [641] = 'RDM Artifact Quest I',
    [642] = 'RDM Artifact Quest II',
    [643] = 'RDM Artifact Quest III',
    [644] = 'THF Artifact Quest I',
    [645] = 'THF Artifact Quest II',
    [646] = 'THF Artifact Quest III',
    [647] = 'PLD Artifact Quest I',
    [648] = 'PLD Artifact Quest II',
    [649] = 'PLD Artifact Quest III',
    [650] = 'DRK Artifact Quest I',
    [651] = 'DRK Artifact Quest II',
    [652] = 'DRK Artifact Quest III',
    [653] = 'BST Artifact Quest I',
    [654] = 'BST Artifact Quest II',
    [655] = 'BST Artifact Quest III',
    -- 'Quests (Artifact 2)'
    [656] = 'BRD Artifact Quest I',
    [657] = 'BRD Artifact Quest II',
    [658] = 'BRD Artifact Quest III',
    [659] = 'RNG Artifact Quest I',
    [660] = 'RNG Artifact Quest II',
    [661] = 'RNG Artifact Quest III',
    [662] = 'SAM Artifact Quest I',
    [663] = 'SAM Artifact Quest II',
    [664] = 'SAM Artifact Quest III',
    [665] = 'Nin Artifact Quest I',
    [666] = 'NIN Artifact Quest II',
    [667] = 'NIN Artifact Quest III',
    [668] = 'DRG Artifact Quest I',
    [669] = 'DRG Artifact Quest II',
    [670] = 'DRG Artifact Quest III',
    [671] = 'SMN Artifact Quest I',
    [672] = 'SMN Artifact Quest II',
    [673] = 'SMN Artifact Quest III',
    [674] = 'BLU Artifact Quest I',
    [675] = 'BLU Artifact Quest II',
    [676] = 'BLU Artifact Quest III',
    [677] = 'COR Artifact Quest I',
    [678] = 'COR Artifact Quest II',
    [679] = 'COR Artifact Quest III',
    [680] = 'PUP Artifact Quest I',
    [681] = 'PUP Artifact Quest II',
    [682] = 'PUP Artifact Quest III',
    -- 'Quests (Artifact 3)'
    [683] = 'DNC Artifact Quest I',
    [684] = 'DNC Artifact Quest II',
    [685] = 'DNC Artifact Quest III',
    [686] = 'SCH Artifact Quest I',
    [687] = 'SCH Artifact Quest II',
    [688] = 'SCH Artifact Quest III',
    [689] = 'GEO Artifact Quest I',
    [690] = 'GEO Artifact Quest II',
    [691] = 'GEO Artifact Quest III',
    [692] = 'RUN Artifact Quest I',
    [693] = 'RUN Artifact Quest II',
    [694] = 'RUN Artifact Quest III',
    -- 'Level Cap Increase'
    [705] = 'Level Cap Increase: 55',
    [706] = 'Level Cap Increase: 60',
    [707] = 'Level Cap Increase: 65',
    [708] = 'Level Cap Increase: 70',
    [709] = 'Level Cap Increase: 75',
    [710] = 'Level Cap Increase: 80',
    [711] = 'Level Cap Increase: 85',
    [712] = 'Level Cap Increase: 90',
    [713] = 'Level Cap Increase: 95',
    [714] = 'Level Cap Increase: 99',
    [871] = 'Level Cap Increase: 75 (BLU)',
    [872] = 'Level Cap Increase: 75 (COR)',
    [873] = 'Level Cap Increase: 75 (PUP)',
    [874] = 'Level Cap Increase: 75 (DNC)',
    [875] = 'Level Cap Increase: 75 (SCH)',
    [876] = 'Level Cap Increase: 75 (GEO)',
    [877] = 'Level Cap Increase: 75 (RUN)',
    -- 'Storage Expansion'
    [] = 'Inventory Expansion 35',
    [] = 'Inventory Expansion 40',
    [] = 'Inventory Expansion 45',
    [] = 'Inventory Expansion 50',
    [] = 'Inventory Expansion 55',
    [] = 'Inventory Expansion 60',
    [] = 'Inventory Expansion 65',
    [] = 'Inventory Expansion 70',
    [] = 'Inventory Expansion 75',
    [] = 'Inventory Expansion 80',
    [] = 'Mog Safe Expansion: 60',
    [] = 'Mog Safe Expansion: 70',
    [] = 'Mog Safe Expansion: 80',
    -- 'Quests (Weapon Skills)'
    [839] = 'Asuran Fists',
    [840] = 'Evisceration',
    [841] = 'Savage Blade',
    [842] = 'Ground Strike',
    [843] = 'Decimation',
    [844] = 'Steel Cyclone',
    [845] = 'Spiral Hell',
    [846] = 'Impulse Drive',
    [847] = 'Blade: Ku',
    [848] = 'Tachi: Kasha',
    [849] = 'Black Halo',
    [850] = 'Retribution',
    [851] = 'Empyreal Arrow',
    [852] = 'Detonator',
    --'Missions (Rhapsodies of Vana\'diel)'
    [] = 'Rhapsodies of Vana\'diel Chapter 1-1',
    [1374] = 'Rhapsodies of Vana\'diel Chapter 1-2',
    -- 'Missions (San d\'Oria)'
    [1313] = 'San d\'Oria Rank 1-1',
    -- 'Missions (Bastok)'
    [1333] = 'Bastok Rank 1-1',
    -- 'Missions (Windurst)'
    [1353] = 'Windurst Rank 1-1',
    -- 'Missions (Zilart)'
    [1377] = 'Rise of the Zilart 1',
    -- 'Missions (Promathia)'
    [1393] = 'Chains of Promathia Chapter 1',
    -- 'Missions (Aht Urhgan)'
    [1410] = 'Treasures of Aht Urhgan 1',
    -- 'Missions (Altana)'
    [1402] = 'Wings of the Goddess 1',
    -- 'Missions (Adoulin)'
    [1426] = 'Seekers of Adoulin Chapter 1',
    -- 'Combat (General)'
    [12] = 'Vanquish Multiple Enemies I',
    [] = 'Vanquish Multiple Enemies II',
    [] = 'Vanquish Multiple Enemies III',
    [15] = 'Level Sync to Vanquish Enemies I',
    [117] = 'Level Sync to Vanq. Enemies II',
    [] = 'Deal 500+ Damage',
    [] = 'Deal 1000+ Damage',
    [] = 'Deal 1500+ Damage',
    [] = 'Deal 2000+ Damage',
    [19] = 'Deal 10-20 Damage',
    [] = 'Deal 110-120 Damage',
    [] = 'Deal 310-320 Damage',
    [] = 'Deal 510-520 Damage',
    [] = 'Deal 1110-1120 Damage',
    [29] = 'Total Damage I',
    [] = 'Total Damage II',
    [] = 'Total Damage III',
    [31] = 'Total Healing I',
    [] = 'Total Healing II',
    [] = 'Total Healing III',
    [33] = 'Total Damage Taken I',
    [] = 'Total Damage Taken II',
    [] = 'Total Damage Taken III',
    [45] = 'Weapon Skills I',
    [] = 'Heal for 500+ HP',
    [] = 'Heal for 750+ HP',
    -- 'Combat (Spoils) 1'
    [] = 'Spoils (Fire Crystal)',
    [] = 'Spoils (Ice Crystal)',
    [] = 'Spoils (Wind Crystal)',
    [74] = 'Spoils (Earth Crystal)',
    [] = 'Spoils (Lightning Crystal)',
    [] = 'Spoils (Water Crystal)',
    [] = 'Spoils (Light Crystal)',
    [] = 'Spoils (Dark Crystal)',
    [] = 'Spoils (Flame Geode)',
    [] = 'Spoils (Snow Geode)',
    [] = 'Spoils (Breeze Geode)',
    [] = 'Spoils (Soil Geode)',
    [] = 'Spoils (Thunder Geode)',
    [] = 'Spoils (Aqua Geode)',
    [] = 'Spoils (Light Geode)',
    [] = 'Spoils (Shadow Geode)',
    [] = 'Spoils (Ifritite)',
    [] = 'Spoils (Shivite)',
    [] = 'Spoils (Garudite)',
    [] = 'Spoils (Titanite)',
    [] = 'Spoils (Ramuite)',
    [] = 'Spoils (Leviatite)',
    [] = 'Spoils (Carbite)',
    [] = 'Spoils (Fenrite)',
    -- 'Combat (Spoils) 2'
    [] = 'Spoils (Bat Wing)',
    [] = 'Spoils (Black Tiger Fang)',
    [] = 'Spoils (Flint Stone)',
    [] = 'Spoils (Rabbit Hide)',
    [] = 'Spoils (Honey)',
    [] = 'Spoils (Sheepskin)',
    [] = 'Spoils (Lizard Skin)',
    [] = 'Spoils (Beetle Shell)',
    [] = 'Spoils (Zeruhn Soot)',
    [] = 'Spoils (Silver Name Tag)',
    [] = 'Spoils (Quadav Helm)',
    [] = 'Spoils (Treant Bulb)',
    [] = 'Spoils (Wild Onion)',
    [] = 'Spoils (Sleepshroom)',
    [] = 'Spoils (Sand Bat Fang)',
    [] = 'Spoils (Zinc Ore)',
    [] = 'Spoils (Giant Bird Feather)',
    [] = 'Spoils (Three-leaf Mandragora Bud)',
    [] = 'Spoils (Four-leaf Mandragora Bud)',
    [] = 'Spoils (Cornette)',
    [] = 'Spoils (Yuhtunga Sulfur)',
    [] = 'Spoils (Snobby Letter)',
    [] = 'Spoils (Yagudo Bead Necklace)',
    [] = 'Spoils (Woozyshroom)',
    [] = 'Spoils (Beehive Chip)',
    [] = 'Spoils (Remi Shell)',
    [] = 'Spoils (Twinstone Earring)',
    -- 'Combat (Original Areas 1)'
    [] = 'Conflict: West Ronfaure',
    [] = 'Subjugation: Jaggedy-Eared Jack',
    [] = 'Conflict: East Ronfaure',
    [] = 'Subjugation: Swamfisk',
    [] = 'Conflict: Ghelsba Outpost',
    [] = 'Subjugation: Thousandarm Deshglesh',
    [] = 'Conflict: Fort Ghelsba',
    [] = 'Subjugation: Hundredscar Hajwaj',
    [] = 'Conflict: Yughott Grotto',
    [] = 'Subjugation: Ashmaker Gotblut',
    [] = 'Conflict: King Ranperre\'s Tomb',
    [] = 'Subjugation: Barbastelle',
    [] = 'Conflict: Bostaunieux Oubliette',
    [] = 'Subjugation: Bloodsucker',
    [] = 'Conflict: Valkurm Dunes',
    [] = 'Subjugation: Valkurm Emperor',
    [] = 'Conflict: Konschtat Highlands',
    [] = 'Subjugation: Bendigeit Vran',
    [] = 'Conflict: Gusgen Mines',
    [] = 'Subjugation: Juggler Hecatomb',
    [] = 'Conflict: La Theine Plateau',
    [] = 'Subjugation: Bloodtear Baldurf',
    [] = 'Conflict: Ordelle\'s Caves',
    [] = 'Subjugation: Morbolger',
    -- 'Combat (Original Areas 2)'
    [] = 'Conflict: Jugner Forest',
    [] = 'Subjugation: King Arthro',
    [] = 'Conflict: Batallia Downs',
    [] = 'Subjugation: Lumber Jack',
    [] = 'Conflict: Eldieme Necropolis',
    [] = 'Subjugation: Cwn Cyrff',
    [] = 'Conflict: Davoi',
    [] = 'Subjugation: Hawkeyed Dnatbat',
    [] = 'Conflict: North Gustaburg',
    [] = 'Subjugation: Maighdean Uaine',
    [] = 'Conflict: South Gustaburg',
    [] = 'Subjugation: Carnero',
    [] = 'Conflict: Zeruhn Mines',
    [] = 'Conflict: Palborough Mines',
    [] = 'Subjugation: Zi\'Ghi Boneeater',
    [] = 'Conflict: Dangruf Wadi',
    [] = 'Subjugation: Teporingo',
    [] = 'Conflict: Pashhow Marshlands',
    [] = 'Subjugation: Ni\'Zho Bladebender',
    [] = 'Conflict: Rolanberry Fields',
    [] = 'Subjugation: Simurgh',
    [] = 'Conflict: Crawlers\' Nest',
    [] = 'Subjugation: Demonic Tiphia',
    [] = 'Conflict: Beadeaux',
    [] = 'Subjugation: Zo\'Khu Blackcloud',
    -- 'Combat (Original Areas 3)'
    [] = 'Conflict: West Sarutabaruta',
    [] = 'Subjugation: Nunyenunc',
    [] = 'Conflict: East Sarutabaruta',
    [] = 'Subjugation: Spiny Spipi',
    [] = 'Conflict: Giddeus',
    [] = 'Subjugation: Hoo Mjuu the Torrent',
    [] = 'Conflict: Toraimarai Canal',
    [] = 'Subjugation: Oni Carcass',
    [] = 'Conflict: Inner Horutoto Ruins',
    [] = 'Subjugation: Maltha',
    [] = 'Conflict: Outer Horutoto Ruins',
    [] = 'Subjugation: Bomb King',
    [] = 'Conflict: Buburimu Peninsula',
    [] = 'Subjugation: Helldiver',
    [] = 'Conflict: Tahrongi Canyon',
    [] = 'Subjugation: Serpopard Ishtar',
    [] = 'Conflict: Maze of Shakhrami',
    [] = 'Subjugation: Argus',
    [] = 'Conflict: Meriphataud Mountains',
    [] = 'Subjugation: Daggerclaw Dracos',
    [] = 'Conflict: Sauromugue Champaign',
    [] = 'Subjugation: Roc',
    [] = 'Conflict: Garlaige Citadel',
    [] = 'Subjugation: Serket',
    [] = 'Conflict: Castle Oztroja',
    [] = 'Subjugation: Lii Jixa the Somnolist',
    -- 'Combat (Original Areas 4)'
    [] = 'Conflict: Beaucedine Glacier',
    [] = 'Subjugation: Nue',
    [] = 'Conflict: Ranguemont Pass',
    [] = 'Subjugation: Gloom Eye',
    [] = 'Conflict: Fei\'Yin',
    [] = 'Subjugation: Goliath',
    [] = 'Conflict: Xarcabard',
    [] = 'Subjugation: Biast',
    [] = 'Conflict: Castle Zvahl Baileys',
    [] = 'Subjugation: Duke Haborym',
    [] = 'Conflict: Castle Zvahl Keep',
    [] = 'Subjugation: Baron Vapula',
    [] = 'Conflict: Qufim Island',
    [] = 'Subjugation: Dosetsu Tree',
    [] = 'Conflict: Lower Delkfutt\'s Tower',
    [] = 'Subjugation: Epialtes',
    [] = 'Conflict: Middle Delkfutt\'s Tower',
    [] = 'Subjugation: Ogygos',
    [] = 'Conflict: Upper Delkfutt\'s Tower',
    [] = 'Subjugation: Enkelados',
    [] = 'Conflict: Behemoth\'s Dominion',
    -- 'Combat (Adoulin 1)'
    [] = 'Conflict: Rala Waterways I',
    [] = 'Conflict: Rala Waterways II',
    [] = 'Conflict: Rala Waterways III',
    [] = 'Conflict: Ceizak Battlegrounds I',
    [] = 'Conflict: Ceizak Battlegrounds II',
    [] = 'Conflict: Ceizak Battlegrounds III',
    [] = 'Conflict: Yahse Hunting Grounds I',
    [] = 'Conflict: Yahse Hunting Grounds II',
    [] = 'Conflict: Yahse Hunting Grounds III',
    [] = 'Conflict: Foret de Hennitiel I',
    [] = 'Conflict: Foret de Hennitiel II',
    [] = 'Conflict: Foret de Hennitiel III',
    [] = 'Conflict: Morimar Basalt Fields I',
    [] = 'Conflict: Morimar Basalt Fields II',
    [] = 'Conflict: Morimar Basalt Fields III',
    [] = 'Conflict: Yorcia Weald I',
    [] = 'Conflict: Yorcia Weald II',
    [] = 'Conflict: Yorcia Weald III',
    [] = 'Conflict: Marjami Ravine I',
    [] = 'Conflict: Marjami Ravine II',
    [] = 'Conflict: Marjami Ravine III',
    -- 'Combat (Adoulin 2)'
    [] = 'Conflict: Kamihr Drifts I',
    [] = 'Conflict: Kamihr Drifts II',
    [] = 'Conflict: Kamihr Drifts III',
    [] = 'Conflict: Sih Gates I',
    [] = 'Conflict: Sih Gates II',
    [] = 'Conflict: Sih Gates III',
    [] = 'Conflict: Moh Gates I',
    [] = 'Conflict: Moh Gates II',
    [] = 'Conflict: Moh Gates III',
    [] = 'Conflict: Cirdas Caverns I',
    [] = 'Conflict: Cirdas Caverns II',
    [] = 'Conflict: Cirdas Caverns III',
    [] = 'Conflict: Dho Gates I',
    [] = 'Conflict: Dho Gates II',
    [] = 'Conflict: Dho Gates III',
    [] = 'Conflict: Woh Gates I',
    [] = 'Conflict: Woh Gates II',
    [] = 'Conflict: Woh Gates III',
    [] = 'Conflict: Outer Ra\'Kaznar I',
    [] = 'Conflict: Outer Ra\'Kaznar II',
    [] = 'Conflict: Outer Ra\'Kaznar III',
    [] = 'Conflict: Ra\'Kaznar Inner Court I',
    [] = 'Conflict: Ra\'Kaznar Inner Court II',
    [] = 'Conflict: Ra\'Kaznar Inner Court III',
    -- 'Combat (Zilart 1)'
    [] = 'Conflict: Sanctuary of Zi\'Tah',
    [] = 'Conflict: Ro\'Maeve',
    [] = 'Conflict: Boyahda Tree',
    [] = 'Conflict: Dragon\'s Aery',
    [] = 'Conflict: Eastern Altepa Desert',
    [] = 'Conflict: Western Altepa Desert',
    [] = 'Conflict: Quicksand Caves',
    [] = 'Conflict: Gustav Tunnel',
    [] = 'Conflict: Kuftal Tunnel',
    [] = 'Conflict: Cape Teriggan',
    [] = 'Conflict: Valley of Sorrows',
    [] = 'Conflict: Yuhtunga Jungle',
    -- 'Combat (Zilart 2)'
    [] = 'Conflict: Sea Serpent Grotto',
    [] = 'Conflict: Yhoator Jungle',
    [] = 'Conflict: Temple of Uggalepih',
    [] = 'Conflict: Den of Rancor',
    [] = 'Conflict: Ifrit\'s Cauldron',
    [424] = 'Conflict: Ru\'Aun Gardens',
    [] = 'Conflict: Ve\'Lugannon Palace',
    [] = 'Conflict: Shrine of Ru\'Avitau',
    [] = 'Conflict: Labyrinth of Onzozo',
    [] = 'Conflict: Korroloka Tunnel',
    -- 'Combat (Promathia 1)'
    [] = 'Conflict: Oldton Movalpolos',
    [] = 'Conflict: Newton Movalpolos',
    [] = 'Conflict: Lufaise Meadows',
    [] = 'Conflict: Misareaux Coast',
    [] = 'Conflict: Phomiuna Aqueducts',
    [] = 'Conflict: Riverne - Site #A01',
    [] = 'Conflict: Riverne - Site #B01',
    [] = 'Conflict: Sacrarium',
    [] = 'Conflict: Promyvion - Holla',
    [] = 'Conflict: Promyvion - Dem',
    [] = 'Conflict: Promyvion - Mea',
    [] = 'Conflict: Promyvion - Vahzl',
    -- 'Combat (Promathia 2)'
    [] = 'Conflict: Al\'Taieu',
    [] = 'Conflict: Grand Palace of Hu\'Xzoi',
    [] = 'Conflict: Garden of Ru\'Hmet',
    [] = 'Conflict: Carpenters\' Landing',
    [] = 'Conflict: Bibiki Bay',
    [] = 'Conflict: Attohwa Chasm',
    [] = 'Conflict: Pso\'Xja',
    [] = 'Conflict: Uleguerand Range',
    -- 'Combat (Aht Urhgan)'
    [] = 'Conflict: Bhaflau Thickets',
    [] = 'Conflict: Mamook',
    [] = 'Conflict: Wajaom Woodlands',
    [] = 'Conflict: Aydeewa Subterrane',
    [] = 'Conflict: Halvung',
    [] = 'Conflict: Mount Zhayolm',
    [] = 'Conflict: Caedarva Mire',
    [] = 'Conflict: Arrapago Reef',
    [] = 'Conflict: Alza. Undersea Ruins',
    -- 'Combat (Goddess 1)'
    [] = 'Conflict: East Ronfaure [S]',
    [] = 'Conflict: Jugner Forest [S]',
    [] = 'Conflict: Batallia Downs [S]',
    [] = 'Conflict: La Vaule [S]',
    [] = 'Conflict: Eldieme Necropolis [S]',
    [] = 'Conflict: North Gustaberg [S]',
    [] = 'Conflict: Grauberg [S]',
    [] = 'Conflict: Vunkerl Inlet [S]',
    [] = 'Conflict: Pashhow Marshlands [S]',
    [] = 'Conflict: Rolanberry Fields [S]',
    [] = 'Conflict: Beadeaux [S]',
    [] = 'Conflict: Crawlers\' Nest [S]',
    -- 'Combat (Goddess 2)'
    [] = 'Conflict: West Sarutabaruta [S]',
    [] = 'Conflict: Fort Karugo-Narugo [S]',
    [] = 'Conflict: Meriph. Mountains [S]',
    [] = 'Conflict: Sauro. Champaign [S]',
    [] = 'Conflict: Castle Oztroja [S]',
    [] = 'Conflict: Garlaige Citadel [S]',
    [] = 'Conflict: Beaucedine Glacier [S]',
    [] = 'Conflict: Xarcabard [S]',
    [] = 'Conflict: Castle Zvahl Baileys [S]',
    [] = 'Conflict: Castle Zvahl Keep [S]',
    -- 'Combat (Abyssea)'
    [] = 'Conflict: Abyssea - La Theine',
    [] = 'Conflict: Abyssea - Konshtat',
    [] = 'Conflict: Abyssea - Tahrongi',
    [] = 'Conflict: Abyssea - Attohwa',
    [] = 'Conflict: Abyssea - Misareaux',
    [] = 'Conflict: Abyssea - Vunkerl',
    [] = 'Conflict: Abyssea - Altepa',
    [] = 'Conflict: Abyssea - Uleguerand',
    [] = 'Conflict: Abyssea - Grauberg',
    -- 'Combat (Escha 1)'
    [885] = 'Conflict: Escha - Zi\'Tah I',
    [886] = 'Conflict: Escha - Zi\'Tah II', -- buggards
    [887] = 'Conflict: Escha - Zi\'Tah III', -- tarichuks
    [888] = 'Conflict: Escha - Zi\'Tah IV', -- s.dragons
    [889] = 'Conflict: Escha - Zi\'Tah V', -- mosquitos
    [901] = 'Conflict: Escha - Zi\'Tah VI', -- puks
    [] = 'Conflict: Escha - Zi\'Tah VII',
    [] = 'Conflict: Escha - Ru\'Aun I',
    [] = 'Conflict: Escha - Ru\'Aun II',
    [] = 'Conflict: Escha - Ru\'Aun III',
    [] = 'Conflict: Escha - Ru\'Aun IV',
    [] = 'Conflict: Escha - Ru\'Aun V',
    [] = 'Conflict: Escha - Ru\'Aun VI',
    [] = 'Conflict: Escha - Ru\'Aun VII',
    [] = 'Conflict: Escha - Ru\'Aun VIII',
    [] = 'Conflict: Escha - Ru\'Aun IX',
    [] = 'Conflict: Escha - Ru\'Aun X',
    -- 'Combat (Escha 2)'
    [] = 'Conflict: Reisenjima I',
    [] = 'Conflict: Reisenjima II',
    [] = 'Conflict: Reisenjima III',
    [946] = 'Conflict: Reisenjima IV', -- faaz
    [947] = 'Conflict: Reisenjima V', 
    [948] = 'Conflict: Reisenjima VI', -- mosquitos
    [949] = 'Conflict: Reisenjima VII',
    [] = 'Conflict: Reisenjima VIII',
    [] = 'Conflict: Reisenjima IX',
    [] = 'Conflict: Reisenjima X',
    [] = 'Conflict: Reisenjima XI',
    -- 'Fishing: General'
    [1000] = 'Speak to Fisherman\'s Guild Master',
    [] = 'Reel in a Catch',
    [] = 'Reel in Multiple Small Fish I',
    [] = 'Reel in Multiple Big Fish I',
    [] = 'Reel in Multiple Rusted Objects',
    [] = 'Total Enemies Reeled In',
    [] = 'Participate in Fish Ranking',
    [] = 'Total Catches (Anywhere)',
    [] = 'Total Catches (Saltwater)',
    [] = 'Total Catches (Freshwater)',
    [] = 'Fish with a Willow Fishing Rod',
    [] = 'Fish with a Yew Fishing Rod',
    [] = 'Fish with a Bamboo Fishing Rod',
    -- 'Fishing: Tenacity'
    [] = 'Reel in 10 Different Catches',
    [] = 'Reel in 25 Different Catches',
    [] = 'Reel in 50 Different Catches',
    [] = 'Reel in 75 Different Catches',
    [] = 'Reel in 100 Different Catches',
    [] = 'Reel Endurance 1',
    [] = 'Reel Endurance 2',
    [] = 'Reel Endurance 3',
    [] = 'Reel Endurance 4',
    [] = 'Reel Endurance 5',
    [] = 'Reel Endurance 6',
    [] = 'Reel Endurance 7',
    [] = 'Reel Endurance 8',
    [] = 'Catch Size and Weight',
    [] = 'Region: Ronfaure',
    [] = 'Region: Gustaberg',
    [] = 'Region: Sarutabaruta',
    [] = 'Region: Zulkheim',
    [] = 'Region: Kolshuhu',
    [] = 'Region: Norvallen',
    [] = 'Region: Derfland',
    [] = 'Region: Aragoneau',
    [] = 'Region: Qufim',
    [] = 'Region: Fauregandi',
    [] = 'Region: Kuzotz',
    [] = 'Region: Vollbow',
    [] = 'Region: Elshimo Lowlands',
    [] = 'Region: Elshimo Uplands',
    [] = 'Region: Li\'Telor',
    [] = 'Region: Selbina - Mhuara Ferry',
    -- 'Crafting: General'
    [] = 'Total Successful Synthesis Attempts'
    -- 'Crafting: Escutcheons (Woodworking)'
    [] = 'Guild Master\'s Request 1',
    [] = 'Guild Master\'s Request 2',
    [] = 'Guild Master\'s Request 3',
    [] = 'Guild Master\'s Request 4',
    -- 'Crafting: Escutcheons (Clothcraft)'
    [] = 'Guild Master\'s Request 1',
    [] = 'Guild Master\'s Request 2',
    [] = 'Guild Master\'s Request 3',
    [] = 'Guild Master\'s Request 4',
    -- 'Crafting: Escutcheons (Alchemy)'
    [] = 'Guild Master\'s Request 1',
    [] = 'Guild Master\'s Request 2',
    [] = 'Guild Master\'s Request 3',
    [] = 'Guild Master\'s Request 4',
    -- 'Crafting: Escutcheons (Bonecraft)'
    [] = 'Guild Master\'s Request 1',
    [] = 'Guild Master\'s Request 2',
    [] = 'Guild Master\'s Request 3',
    [] = 'Guild Master\'s Request 4',
    -- 'Crafting: Escutcheons (Cooking)'
    [] = 'Guild Master\'s Request 1',
    [] = 'Guild Master\'s Request 2',
    [] = 'Guild Master\'s Request 3',
    [] = 'Guild Master\'s Request 4',
    -- 'Crafting: Escutcheons (Goldsmithing)'
    [] = 'Guild Master\'s Request 1',
    [] = 'Guild Master\'s Request 2',
    [] = 'Guild Master\'s Request 3',
    [] = 'Guild Master\'s Request 4',
    -- 'Crafting: Escutcheons (Leathercraft)'
    [] = 'Guild Master\'s Request 1',
    [] = 'Guild Master\'s Request 2',
    [] = 'Guild Master\'s Request 3',
    [] = 'Guild Master\'s Request 4',
    -- 'Crafting: Escutcheons (Smithing)'
    [] = 'Guild Master\'s Request 1',
    [] = 'Guild Master\'s Request 2',
    [] = 'Guild Master\'s Request 3',
    [] = 'Guild Master\'s Request 4',
    -- 'Harvesting (General)'
    [] = 'Total Successful Harvesting Attempts',
    [] = 'Total Suc. Harvesting Attempts II',
    -- 'Harvesting (Original Areas)'
    [] = 'Harvesting: East Ronfaure',
    [] = 'Harvesting: Ghelsba Outpost',
    [] = 'Harvesting: Gusgen Mines',
    [] = 'Harvesting: Jugner Forest',
    [] = 'Harvesting: Zeruhn Mines',
    [] = 'Harvesting: Palborough Mines',
    [] = 'Harvesting: West Sarutabaruta',
    [] = 'Harvesting: Giddeus',
    [] = 'Harvesting: Buburimu Penisula',
    [] = 'Harvesting: Tahrongi Canyon',
    [] = 'Harvesting: Maze of Shakhrami',
    [] = 'Harvesting: Yughott Grotto',
    -- 'Harvesting (Adoulin 1)'
    [] = 'Harvesting: Ceizak Battlegrounds I',
    [] = 'Harvesting: Ceizak Battlegrounds II',
    [] = 'Harvesting: Yahse Hunting Grounds I',
    [] = 'Harvesting: Yahse Hunting Grounds II',
    [] = 'Harvesting: Foret de Hennetiel I',
    [] = 'Harvesting: Foret de Hennetiel II',
    [] = 'Harvesting: Morimar Basalt Fields I',
    [] = 'Harvesting: Morimar Basalt Fields II',
    [] = 'Harvesting: Yorcia Weald I',
    [] = 'Harvesting: Yorcia Weald II',
    [] = 'Harvesting: Marjami Ravine I',
    [] = 'Harvesting: Marjami Ravine II',
    [] = 'Harvesting: Kamihr Drifts I',
    [] = 'Harvesting: Kamihr Drifts II',
    [] = 'Harvesting: Sih Gates I',
    [] = 'Harvesting: Sih Gates II',
    [] = 'Harvesting: Moh Gates I',
    [] = 'Harvesting: Moh Gates II',
    [] = 'Harvesting: Cirdas Caverns I',
    [] = 'Harvesting: Cirdas Caverns II',
    [] = 'Harvesting: Dho Gates I',
    [] = 'Harvesting: Dho Gates II',
    [] = 'Harvesting: Woh Gates I',
    [] = 'Harvesting: Woh Gates II',
    [] = 'Harvesting: Outer Ra\'Kaznar I',
    [] = 'Harvesting: Outer Ra\'Kaznar II',
    -- 'Harvesting (Zilart)'
    [] = 'Harvesting: Yuhtunga Jungle',
    [] = 'Harvesting: Yhoator Jungle',
    [] = 'Harvesting: Ifrit\'s Cauldron',
    [] = 'Harvesting: Korroloka Tunnel',
    -- 'Harvesting (Promathia)'
    [] = 'Harvesting: Oldton Movalpolos',
    [] = 'Harvesting: Newton Movalpolos',
    [] = 'Harvesting: Lufaise Meadows',
    [] = 'Harvesting: Misareaux Coast',
    [] = 'Harvesting: Carpenters\' Landing',
    [] = 'Harvesting: Attohwa Chasm',
    -- 'Harvesting (Aht Urhgan)'
    [] = 'Harvesting: Bhaflau Thickets',
    [] = 'Harvesting: Mamook',
    [] = 'Harvesting: Wajaom Woodlands',
    [] = 'Harvesting: Halvung',
    [] = 'Harvesting: Mount Zhayolm',
    [] = 'Harvesting: Caedarva Mire',
    -- 'Harvesting (Goddess)'
    [] = 'Harvesting: East Ronfaure [S]',
    [] = 'Harvesting: Jugner Forest [S]',
    [] = 'Harvesting: North Gustaberg [S]',
    [] = 'Harvesting: Grauberg [S]',
    [] = 'Harvesting: West Sarutabaruta [S]',
    [] = 'Harvesting: Fort Karugo-Narugo [S]',
    -- 'Harvesting (Abyssea)'
    [] = 'Harvesting: Abyssea - La Thiene',
    [] = 'Harvesting: Abyssea - Tahronghi',
    [] = 'Harvesting: Abyssea - Attohwa',
    [] = 'Harvesting: Abyssea - Misareaux',
    [] = 'Harvesting: Abyssea - Grauberg',
    -- 'Content (Ambuscade)'
    [3758] = 'Ambuscade Primer Vol. 1 (Daily)',
    [3759] = 'Ambuscade Primer Vol. 2 (Daily)',
    [3995] = 'Intense Ambuscade (M)',
    [3760] = 'Ambuscade (W)',
    [] = 'Ambuscade Primer Vol. 1',
    [3999] = 'Ambuscade Primer Vol. 2',
    -- 'Lair Reives'
    [349] = 'Lair Reives: Ceizak Battlegrounds',
    [350] = 'Lair Reives: Yahse Hunting Grounds',
    [351] = 'Lair Reives: Foret de Hennetiel',
    [352] = 'Lair Reives: Morimar Basalt Fields',
    [] = 'Lair Reives: Yorcia Weald',
    [] = 'Lair Reives: Marjami Ravine',
    [] = 'Lair Reives: Kamihr Drifts',
    [] = 'Lair Reives: Cirdas Caverns',
    [] = 'Lair Reives: Outer Ra\'Kaznar',
    [] = 'Lair Reives: Ra\'Kaznar Inner Court',
    -- 'Colonization Reives'
    [361] = 'Colonization Reives: Ceizak',
    [362] = 'Colonization Reives: Yahse',
    [363] = 'Colonization Reives: Hennetiel',
    [364] = 'Colonization Reives: Morimar',
    [365] = 'Colonization Reives: Yorcia Weald',
    [366] = 'Colonization Reives: Marjami Ravine',
    [367] = 'Colonization Reives: Kamihr Drifts',
    [368] = 'Colonization Reives: Sih Gates',
    [369] = 'Colonization Reives: Moh Gates',
    [370] = 'Colonization Reives: Cirdas Caverns',
    [371] = 'Colonization Reives: Dho Gates',
    [372] = 'Colonization Reives: Woh Gates',
    [498] = 'Colonization Reives: Outer Ra\'Kaznar',
    [766] = 'Colonization Reives: Ra\'Kaznar I.C.',
    -- 'Wildskeeper Reives'
    [373] = 'Subjugation: Colkhab',
    [374] = 'Subjugation: Tchakka',
    [375] = 'Subjugation: Achuka',
    [376] = 'Subjugation: Yumcax',
    [377] = 'Subjugation: Hurkan',
    [378] = 'Subjugation: Kumhau',
    -- 'Content (Other)'
    [] = 'Total Successful Synthesis Attempts',
    [63] = 'Total Suc. Chocobo Digs',
    [65] = 'Mons.: Total Monsters Vanquished',
    [490] = 'Unlock Treasure Chests and Coffers',
    [726] = 'Reaching the Crest',
    [727] = 'Subjugation: Kirin',
    [728] = 'Subjugation: Genbu',
    [729] = 'Subjugation: Suzaku',
    [730] = 'Subjugation: Seiryu',
    [731] = 'Subjugation: Byakko',
    [768] = 'Subjugation: Jailer of Justice',
    [769] = 'Subjugation: Jailer of Hope',
    [770] = 'Subjugation: Jailer of Prudence',
    [771] = 'Subjugation: Jailer of Love',
    [812] = 'Subjugation: Battleclad Chariot',
    [813] = 'Subjugation: Armored Chariot',
    [814] = 'Subjugation: Long-Bowed Chariot',
    [815] = 'Subjugation: Long-Armed Chariot',
    -- 'Content (Dynamis 1)'
    [] = 'Subjugation: Overlord\'s Tombstone',
    [] = 'Subjugation: Bladeburner Rokgevok',
    [] = 'Subjugation: Steelshank Kratzvatz',
    [] = 'Subjugation: Bloodfist Voshgrosh',
    [] = 'Subjugation: Spellspear Djokvukk',
    [] = 'Subjugation: Gu\'Dha Effigy',
    [] = 'Subjugation: Zo\'Pha Forgesoul',
    [] = 'Subjugation: Ra\'Gho Darkfount',
    [] = 'Subjugation: Va\'Zhe Pummelsong',
    [] = 'Subjugation: Bu\'Bho Truesteel',
    [] = 'Subjugation: Tzee Xicu Idol',
    [] = 'Subjugation: Xuu Bhoqa the Enigma',
    [] = 'Subjugation: Fuu Tzapo the Blessed',
    [] = 'Subjugation: Naa Yixo the Stillrage',
    [] = 'Subjugation: Tee Zaksa the Ceaseless',
    [] = 'Subjugation: Goblin Golem',
    [] = 'Subjugation: Quicktrix Hexhands',
    [] = 'Subjugation: Feralox Honeylips',
    [] = 'Subjugation: Scourquix Scaleskin',
    [] = 'Subjugation: Wilywox Tenderpalm',
    -- 'Content (Dynamis 2)'
    [] = 'Subjugation: Angra Mainyu',
    [] = 'Subjugation: Taquede',
    [] = 'Subjugation: Pignonpausard',
    [] = 'Subjugation: Hitaume',
    [] = 'Subjugation: Cavanneche',
    [] = 'Subjugation: Dynamis Lord',
    [] = 'Subjugation: Duke Haures',
    [] = 'Subjugation: Marquis Caim',
    [] = 'Subjugation: Baron Avnas',
    [] = 'Subjugation: Count Haagenti',
    -- 'Content (Limbus)'
    [] = 'Spoils (Ivory Chip)',
    [] = 'Spoils (Scarlet Chip)',
    [] = 'Spoils (Emerald Chip)',
    [] = 'Spoils (Orchid Chip)',
    [] = 'Spoils (Cerulean Chip)',
    [] = 'Spoils (Silver Chip)',
    [] = 'Spoils (Smoky Chip)',
    [] = 'Spoils (Magenta Chip)',
    [] = 'Spoils (Charcoal Chip)',
    [] = 'Spoils (Smalt Chip)',
    [] = 'Subjugation: Proto-Ultima',
    [] = 'Subjugation: Proto-Omega',
    -- 'Content (ZNM)'
    [] = 'Subjugation: Vulpangue',
    [] = 'Subjugation: Chamrosh',
    [] = 'Subjugation: Cheese Hoarder Gigiroon',
    [] = 'Subjugation: Brass Borer',
    [] = 'Subjugation: Claret',
    [] = 'Subjugation: Ob',
    [] = 'Subjugation: Velionis',
    [] = 'Subjugation: Lil\' Apkallu',
    [] = 'Subjugation: Chigre',
    [] = 'Subjugation: Iriz Ima',
    [] = 'Subjugation: Lividroot Amooshah',
    [] = 'Subjugation: Iriri Samariri',
    [] = 'Subjugation: Anantaboga',
    [] = 'Subjugation: Reacton',
    [] = 'Subjugation: Dextrose',
    [] = 'Subjugation: Wulgaru',
    [] = 'Subjugation: Zareehkl the Jubilant',
    [] = 'Subjugation: Verdelet',
    [] = 'Subjugation: Armed Gears',
    [] = 'Subjugation: Gotoh Zha the Redolent',
    [] = 'Subjugation: Dea',
    [] = 'Subjugation: Nosferatu',
    [] = 'Subjugation: Khromasoul Bhurborlor',
    [] = 'Subjugation: Achamoth',
    [] = 'Subjugation: Mahjlaef the Paintorn',
    [] = 'Subjugation: Experimental Lamia',
    [] = 'Subjugation: Nuhn',
    -- 'Content (Vagary)'
    [] = 'Subjugation: Rancibus',
    [] = 'Subjugation: Palloritus',
    [] = 'Subjugation: Putraxia',
    [] = 'Subjugation: Plouton',
    [] = 'Subjugation: Perfidien',
    [] = 'Subj.: Putraxia 1 (W)',
    [] = 'Subj.: Putraxia 2 (W)',
    [] = 'Subj.: Rancibus 1 (W)',
    [] = 'Subj.: Rancibus 2 (W)',
    [] = 'Subj.: Palloritus 1 (W)',
    [] = 'Subj.: Palloritus 2 (W)',
    [] = 'Subj.: Perfidien 1 (W)',
    [] = 'Subj.: Perfidien 2 (W)',
    [] = 'Subjugation: Plouton 1 (W)',
    [] = 'Subjugation: Plouton 2 (W)',
    -- 'Content (Omen)'
    [] = 'Subjugation: Fu',
    [] = 'Subjugation: Kyou',
    [] = 'Subjugation: Kei',
    [] = 'Subjugation: Gin',
    [] = 'Subjugation: Kin',
    -- 'A.M.A.N. Trove'
    [] = 'A.M.A.N. Trove (M)',
    [] = 'Examine a Home Point (M)',
    [] = 'Auction an Item (M)',
    [] = 'Unity Chat Greetings (M)',
    [] = 'Conquest Participation (M)',
    [3773] = 'Besieged Participation (M)',
    [3774] = 'Campaign Participation (M)',
    [] = 'Reive Participation (M)',
    [3777] = 'Ambuscade Participation (M)',
    [] = 'Omen Participation (M)',
    [] = 'Dynamis - Divergence Participation (M)',
    -- 'Content (Odyssey)'
    [] = 'Sheol A',
    [] = 'Sheol B',
    [] = 'Sheol C',
    -- 'Job Levels 1'
    [] = 'Level 30 Warrior',
    [] = 'Level 50 Warrior',
    [] = 'Level 75 Warrior',
    [] = 'Level 99 Warrior',
    [] = 'Level 30 Monk',
    [] = 'Level 50 Monk',
    [] = 'Level 75 Monk',
    [] = 'Level 99 Monk',
    [] = 'Level 30 White Mage',
    [] = 'Level 50 White Mage',
    [] = 'Level 75 White Mage',
    [] = 'Level 99 White Mage',
    [] = 'Level 30 Black Mage',
    [] = 'Level 50 Black Mage',
    [] = 'Level 75 Black Mage',
    [] = 'Level 99 Black Mage',
    [] = 'Level 30 Red Mage',
    [] = 'Level 50 Red Mage',
    [] = 'Level 75 Red Mage',
    [] = 'Level 99 Red Mage',
    [] = 'Level 30 Thief',
    [] = 'Level 50 Thief',
    [] = 'Level 75 Theif',
    [] = 'Level 99 Thief',
    -- 'Job Levels 2'
    [] = 'Level 30 Paladin',
    [] = 'Level 50 Paladin',
    [] = 'Level 75 Paladin',
    [] = 'Level 99 Paladin',
    [] = 'Level 30 Dark Knight',
    [] = 'Level 50 Dark Knight',
    [] = 'Level 75 Dark Knight',
    [] = 'Level 99 Dark Knight',
    [] = 'Level 30 Beastmaster',
    [] = 'Level 50 Beastmaster',
    [] = 'Level 75 Beastmaster',
    [] = 'Level 99 Beastmaster',
    [] = 'Level 30 Bard',
    [] = 'Level 50 Bard',
    [] = 'Level 75 Bard',
    [] = 'Level 99 Bard',
    [] = 'Level 30 Ranger',
    [] = 'Level 50 Ranger',
    [] = 'Level 75 Ranger',
    [] = 'Level 99 Ranger',
    [] = 'Level 30 Samurai',
    [] = 'Level 50 Samurai',
    [] = 'Level 75 Samurai',
    [] = 'Level 99 Samurai',
    -- 'Job Levels 3'
    [] = 'Level 30 Ninja',
    [] = 'Level 50 Ninja',
    [] = 'Level 75 Ninja',
    [] = 'Level 99 Ninja',
    [] = 'Level 30 Dragoon',
    [] = 'Level 50 Dragoon',
    [] = 'Level 75 Dragoon',
    [] = 'Level 99 Dragoon',
    [] = 'Level 30 Summoner',
    [] = 'Level 50 Summoner',
    [] = 'Level 75 Summoner',
    [] = 'Level 99 Summoner',
    [] = 'Level 30 Blue Mage',
    [] = 'Level 50 Blue Mage',
    [] = 'Level 75 Blue Mage',
    [] = 'Level 99 Blue Mage',
    [] = 'Level 30 Corsair',
    [] = 'Level 50 Corsair',
    [] = 'Level 75 Corsair',
    [] = 'Level 99 Corsair',
    [] = 'Level 30 Puppetmaster',
    [] = 'Level 50 Puppetmaster',
    [] = 'Level 75 Puppetmaster',
    [] = 'Level 99 Puppetmaster',
    -- 'Job Levels 4'
    [] = 'Level 30 Dancer',
    [] = 'Level 50 Dancer',
    [] = 'Level 75 Dancer',
    [] = 'Level 99 Dancer',
    [] = 'Level 30 Scholar',
    [] = 'Level 50 Scholar',
    [] = 'Level 75 Scholar',
    [] = 'Level 99 Scholar',
    [] = 'Level 30 Geomancer',
    [] = 'Level 50 Geomancer',
    [] = 'Level 75 Geomancer',
    [] = 'Level 99 Geomancer',
    [] = 'Level 30 Rune Fencer',
    [] = 'Level 50 Rune Fencer',
    [] = 'Level 75 Rune Fencer',
    [] = 'Level 99 Rune Fencer',
    -- 'Fame'
    [] = 'Fame: San d\'Oria',
    [] = 'Fame: Bastok',
    [] = 'Fame: Windurst',
    [] = 'Fame: Norg',
    [] = 'Fame: Abyssea - La Thiene',
    [] = 'Fame: Abyssea - Konschtat',
    [] = 'Fame: Abyssea - Tahrongi',
    [] = 'Fame: Abyssea - Attohwa',
    [] = 'Fame: Abyssea - Misareaux',
    [] = 'Fame: Abyssea - Vunkerl',
    [] = 'Fame: Abyssea - Altepa',
    [] = 'Fame: Abyssea - Uleguerand',
    [] = 'Fame: Abyssea - Grauberg',
    [] = 'Fame: Adoulin',
-- Unity
    -- Unity (Shared A)
    [3000] = 'Unity Communique A (UC)',
    [3001] = 'Home Point Comrade A (UC)',
    [3002] = 'Vanquish Multiple Enemies  A (UC)',
    [3003] = 'Vanquish Aquans A (UC)',
    [3004] = 'Van. Amorphs with Ph. Damage A (UC)',
    [3005] = 'Vanquish Beasts with Magic A (UC)',
    [] = 'Total Suc. Wood. Syntheses A (UC)',
    [] = 'Total Suc. Leath. Syntheses A (UC)',
    [] = 'Total Suc. Mining Attempts A (UC)',
    [3055] = 'Van. Enemies w. Unity Leader A (UC)',
    -- Unity (Shared B)
    [3009] = 'Unity Communique B (UC)',
    [] = 'Chocobo Digging B (UC)',
    [3011] = 'Vanquish Multiple Enemies B (UC)',
    [3012] = 'Vanquish Arcana B (UC)',
    [] = 'Van. Undead with Ph. Damage B (UC)',
    [] = 'Vanquish Plantoids with Magic B (UC)',
    [] = 'Total Suc. Black. Syntheses B (UC)',
    [] = 'Reel in Multiple Small Fish B (UC)',
    [3017] = 'Total Suc. Logging Attempts B (UC)',
    [3056] = 'Van. Enemies w. Unity Leader B (UC)',
    -- Unity (Shared C)
    [3018] = 'Unity Communique C (UC)',
    [3019] = 'Home Point Comrade C (UC)',
    [3020] = 'Vanquish Multiple Enemies C (UC)',
    [] = 'Vanquish Vermin C (UC)',
    [] = 'Van. Birds with Ph. Damage C (UC)',
    [] = 'Vanquish Lizards with Magic C (UC)',
    [] = 'Total Suc. Gold. Syntheses C (UC)',
    [] = 'Reel in Multiple Large Fish C (UC)',
    [] = 'Total Suc. Harvesting Attempts C (UC)',
    [3057] = 'Van. Enemies w. Unity Leader C (UC)',
    -- Unity (Shared D)
    [3027] = 'Unity Communique D (UC)',
    [] = 'Mons.: Tot. Monsters Vanquished D (UC)',
    [3029] = 'Vanquish Multiple Enemies D (UC)',
    [] = 'Vanquish Beasts D (UC)',
    [] = 'Van. Aquans with Ph. Damage D (UC)',
    [] = 'Vanquish Amorphs with Magic D (UC)',
    [] = 'Total Suc. Cloth. Syntheses D (UC)',
    [] = 'Total Suc. Bone. Syntheses D (UC)',
    [] = 'Total Suc. Mining Attempts D (UC)',
    [3058] = 'Van. Enemies w. Unity Leader D (UC)',
    -- Unity (Shared E)
    [3036] = 'Unity Communique E (UC)',
    [3037] = 'Home Point Comrade E (UC)',
    [3038] = 'Vanquish Multiple Enemies E (UC)',
    [3039] = 'Vanquish Plantiods E (UC)',
    [3040] = 'Van. Arcana with Ph. Damage E (UC)',
    [3041] = 'Vanquish Undead with Magic E (UC)',
    [3042] = 'Total Suc. Cook. Syntheses E (UC)',
    [3043] = 'Total Saltwater Catches E (UC)',
    [3044] = 'Total Suc. Logging Attempts E (UC)',
    [3059] = 'Van. Enemies w. Unity Leader E (UC)',
    -- Unity (Shared F)
    [3045] = 'Unity Communique F (UC)',
    [3046] = 'Level sync to vanquish enemies F (UC)',
    [3047] = 'Vanquish Multiple Enemies F (UC)',
    [3048] = 'Vanquish Lizards F (UC)',
    [3049] = 'Van. Vermin with Ph. Damage F (UC)',
    [3050] = 'Vanquish Birds with Magic F (UC)',
    [3051] = 'Total Suc. Alchemy Syntheses F (UC)',
    [3052] = 'Total Freshwater Catches F (UC)',
    [3053] = 'Total Suc. Harvesting Attempts F (UC)',
    [3060] = 'Van. Enemies w. Unity Leader F (UC)',
    -- Unity (Aldo)
    [] = 'Dagger Weapon Skills (UC)',
    [] = 'Conflict: Sanctuary of Zi\'Tah (UC)',
    [] = 'Vanquish Hounds (UC)',
    [] = 'Subjugation: Bastet (UC)',
    [] = 'Heal Unity Allies (UC)',
    [] = 'Spoils (Doll Shard) (UC)',
    [] = 'Conflict: Morimar Basalt Fields (UC)',
    [] = 'Vanquish Dolls (UC)',
    [] = 'Subjugation: Nocuous Weapon (UC)',
    [] = 'Cure Status Ailments (UC)',
    [] = 'Marksmanship Weapon Skills (UC)',
    [] = 'Conflict: Boyahda Tree (UC)',
    [] = 'Vanquish Slimes (UC)',
    [] = 'Subjugation: Aquarius (UC)',
    [] = 'Heal Unity Allies (UC)',
    [] = 'Spoils (Bird Egg) (UC)',
    [] = 'Conflict: Western Altepa Desert (UC)',
    [] = 'Vanquish Crow-Type Birds (UC)',
    [] = 'Subjugation: Cactuar Cantautor (UC)',
    [] = 'Magic Bursts (UC)',
    -- Unity (Apururu)
    [] = 'Club Weapon Skills (UC)',
    [] = 'Conflict: West Sarutabaruta (UC)',
    [] = 'Vanquish Bees (UC)',
    [] = 'Subjugation: Tom Tit Tat (UC)',
    [] = 'Heal Unity Allies (UC)',
    [] = 'Spoils (Silk Thread) (UC)',
    [] = 'Conflict: Buburimu Peninsula (UC)',
    [] = 'Vanquish Crawlers (UC)',
    [] = 'Subjugation: Buburimboo (UC)',
    [] = 'Cure Status Ailments (UC)',
    [] = 'Staff Weapon Skills (UC)',
    [] = 'Conflict: Castle Oztroja (UC)',
    [] = 'Vanquish Ghosts (UC)',
    [] = 'Subj.: Mee Deggi the Punisher (UC)',
    [] = 'Heal Unity Allies (UC)',
    [] = 'Spoils (Saruta Cotton) (UC)',
    [] = 'Conflict: Foret de Hennetiel (UC)',
    [] = 'Vanquish Mandragoras (UC)',
    [] = 'Subj.: Juu Duzu the Whirlwind (UC)',
    [] = 'Magic Bursts (UC)',
    -- Unity (Ayame)
    [] = 'Great Katana Weapon Skills (UC)',
    [] = 'North Gustaberg (UC)',
    [] = 'Vanquish Worms (UC)',
    [] = 'Subjugation: Stinging Sophie (UC)',
    [] = 'Heal Unity Allies (UC)',
    [] = 'Spoils (Cockatrice Meat) (UC)',
    [] = 'Conflict: Yahse Hunting Grounds (UC)',
    [] = 'Vanquish Cockatrices (UC)',
    [] = 'Subjugation: Tococo (UC)',
    [] = 'Cure Status Ailments (UC)',
    [] = 'Archery Weapon Skills (UC)',
    [] = 'Conflict: Crawlers\' Nest (UC)',
    [] = 'Vanquish Lizards (UC)',
    [] = 'Subjugation: Aqrabuamelu (UC)',
    [] = 'Heal Unity Allies (UC)',
    [] = 'Spoils (Land Crab Meat) (UC)',
    [] = 'Conflict: Beadeaux (UC)',
    [] = 'Vanquish Crabs (UC)',
    [] = 'Subjugation: Ge\'Dha Evileye (UC)',
    [] = 'Magic Bursts (UC)',
    -- Unity (Flaviria)
    [] = 'Polearm Weapon Skills (UC)',
    [] = 'Conflict: Cirdas Caverns (UC)',
    [] = 'Vanquish Pugils (UC)',
    [] = 'Subjugation: Hovering Hotpot (UC)',
    [] = 'Heal Unity Allies (UC)',
    [] = 'Spoils (Beetle Shell) (UC)',
    [] = 'Conflict: East Ronfaure (UC)',
    [] = 'Vanquish Beetles (UC)',
    [] = 'Subjugation: Bigmouth Billy (UC)',
    [] = 'Cure Status Ailments (UC)',
    [] = 'Sword Weapon Skills (UC)',
    [] = 'Conflict: Xarcabard (UC)',
    [] = 'Vanquish Goobbues (UC)',
    [] = 'Subjugation: Barbaric Weapon (UC)',
    [] = 'Heal Unity Allies (UC)',
    [] = 'Spoils (Bone Chip) (UC)',
    [] = 'Conflict: Woh Gates (UC)',
    [] = 'Vanquish Skeletons (UC)',
    [] = 'Subjugation: Hyakume (UC)',
    [] = 'Magic Bursts (UC)',
    -- Unity (Invincible Shield)
    [] = 'Axe Weapon Skills (UC)',
    [] = 'Conflict: South Gustaberg (UC)',
    [] = 'Vanquish Sea Monks (UC)',
    [] = 'Subjugation: Leaping Lizzy (UC)',
    [] = 'Heal Unity Allies (UC)',
    [] = 'Spoils (Sleepshroom) (UC)',
    [] = 'Conflict: Pashhow Marshlands (UC)',
    [] = 'Vanquish Funguars (UC)',
    [] = 'Subjugation: Bloodpool Vorax (UC)',
    [] = 'Cure Status Ailments (UC)',
    [] = 'Great Axe Weapon Skills (UC)',
    [] = 'Conflict: Ceizak Battlegrounds (UC)',
    [] = 'Vanquish Flies (UC)',
    [] = 'Subjugation: Be\'Hya Hundredwall (UC)',
    [] = 'Heal Unity Allies (UC)',
    [] = 'Spoils (Raptor Skin) (UC)',
    [] = 'Conflict: Beaucedine Glacier (UC)',
    [] = 'Vanquish Raptors (UC)',
    [] = 'Subjugation: Gargantua (UC)',
    [] = 'Magic Bursts (UC)',
    -- Unity (Jakoh Wahcondalo)
    [] = 'Dagger Weapon Skills (UC)',
    [] = 'Conflict: Yuhtunga Jungle (UC)',
    [] = 'Vanquish Sheep (UC)',
    [] = 'Subj.: Mischievous Micholas (UC)',
    [] = 'Heal Unity Allies (UC)',
    [] = 'Spoils (Scorpion Claw) (UC)',
    [] = 'Conflict: East Sarutabaruta (UC)',
    [] = 'Vanquish Scorpions (UC)',
    [] = 'Subjugation: Sharp-Eared Ropipi (UC)',
    [] = 'Cure Status Ailments (UC)',
    [] = 'Archery Weapon Skills (UC)',
    [] = 'Conflict: Marjami Ravine (UC)',
    [] = 'Vanquish Opo-opos (UC)',
    [] = 'Subjugation: Ah Puch (UC)',
    [] = 'Heal Unity Allies (UC)',
    [] = 'Spoils (Black Tiger Fang) (UC)',
    [] = 'Conflict: Sea Serpent Grotto (UC)',
    [] = 'Vanquish Tigers (UC)',
    [] = 'Subjugation: Fyuu the Seabellow (UC)',
    [] = 'Magic Bursts (UC)',
    -- Unity (Maat)
    [] = 'Hand-to-Hand Weapon Skills (UC)',
    [] = 'Conflict: Yorcia Weald (UC)',
    [] = 'Vanquish Leeches (UC)',
    [] = 'Subjugation: Canal Moocher (UC)',
    [] = 'Heal Unity Allies (UC)',
    [] = 'Spoils (Spider Web) (UC)',
    [] = 'Conflict: Rolanberry Fields (UC)',
    [] = 'Vanquish Spiders (UC)',
    [] = 'Subjugation: Eldritch Edge (UC)',
    [] = 'Cure Status Ailments (UC)',
    [] = 'Great Sword Weapon Skills (UC)',
    [] = 'Conflict: Meriphataud Mountains (UC)',
    [] = 'Vanquish Wyverns (UC)',
    [] = 'Subjugation: Patripatan (UC)',
    [] = 'Heal Unity Allies (UC)',
    [] = 'Spoils (Hecteyes Eye) (UC)',
    [] = 'Conflict: Sauromugue Champaign (UC)',
    [] = 'Vanquish Hecteyes (UC)',
    [] = 'Subjugation: Bashe (UC)',
    [] = 'Magic Bursts (UC)',
    -- Unity (Naja Salaheem)
    [] = 'Club Weapon Skills (UC)',
    [] = 'Conflict: Bhaflau Thickets (UC)',
    [] = 'Vanquish Evil Weapons (UC)',
    [] = 'Subjugation: Emergent Elm (UC)',
    [] = 'Heal Unity Allies (UC)',
    [] = 'Spoils (Puk Wing) (UC)',
    [] = 'Conflict: West Ronfaure (UC)',
    [] = 'Vanquish Puks (UC)',
    [] = 'Subjugation: Fungus Beetle (UC)',
    [] = 'Cure Status Ailments (UC)',
    [] = 'Staff Weapon Skills (UC)',
    [] = 'Conflict: Wajaom Woodlands (UC)',
    [] = 'Vanquish Elementals (UC)',
    [] = 'Subjugation: Jaded Jody (UC)',
    [] = 'Heal Unity Allies (UC)',
    [] = 'Spoils (Dhalmel Meat) (UC)',
    [] = 'Conflict: Kamihr Drifts (UC)',
    [] = 'Vanquish Dhalmel (UC)',
    [] = 'Subjugation: Trembler Tabitha (UC)',
    [] = 'Magic Bursts (UC)',
    -- Unity (Pieuje)
    [] = 'Club Weapon Skills (UC)',
    [] = 'Conflict: Rala Waterways (UC)',
    [] = 'Vanquish Rabbits (UC)',
    [] = 'Subjugation: Rambukk (UC)',
    [] = 'Heal Unity Allies (UC)',
    [] = 'Spoils (Bat Fang) (UC)',
    [] = 'Conflict: La Theine Plateau (UC)',
    [] = 'Vanquish Bats (UC)',
    [] = 'Subjugation: Tumbling Truffle (UC)',
    [] = 'Cure Status Ailments (UC)',
    [] = 'Staff Weapon Skills (UC)',
    [] = 'Conflict: Eldieme Necropolis (UC)',
    [] = 'Vanquish Treants (UC)',
    [] = 'Subjugation: Duke Decapod (UC)',
    [] = 'Heal Unity Allies (UC)',
    [] = 'Spoils (Bomb Ash) (UC)',
    [] = 'Conflict: Davoi (UC)',
    [] = 'Vanquish Bombs (UC)',
    [] = 'Subj.: Poisonhand Gnadgad (UC)',
    [] = 'Magic Bursts (UC)',
    -- Unity (Sylvie)
    [] = 'Club Weapon Skills (UC)',
    [] = 'Conflict: Sih Gates (UC)',
    [] = 'Vanquish Acuex (UC)',
    [] = 'Subjugation: Intulo (UC)',
    [] = 'Heal Unity Allies (UC)',
    [] = 'Spoils (Demon Horn) (UC)',
    [] = 'Conf.: Konschtat Highlands (UC)',
    [] = 'Vanquish Demons (UC)',
    [] = 'Subj.: Marquis Naberius (UC)',
    [] = 'Cure Status Ailments (UC)',
    [] = 'Staff Weapon Skills (UC)',
    [] = 'Conflict: Dho Gates (UC)',
    [] = 'Vanquish Velkk (UC)',
    [] = 'Subjugation: Dune Widow (UC)',
    [] = 'Heal Unity Allies (UC)',
    [] = 'Spoils (Twitherym Wing) (UC)',
    [] = 'Conflict: Qufim Island (UC)',
    [] = 'Vanquish Twitherym (UC)',
    [] = 'Subj.: Atkorkamuy (UC)',
    [] = 'Magic Bursts (UC)',
    -- Unity (Yoran-Oran)
    [] = 'Club Weapon Skills (UC)',
    [] = 'Conflict: Giddeus (UC)',
    [] = 'Vanquish Efts (UC)',
    [] = 'Subj.: Herbage Hunter (UC)',
    [] = 'Heal Unity Allies (UC)',
    [] = 'Spoils (Rotten Meat) (UC)',
    [] = 'Conflict: Moh Gates (UC)',
    [] = 'Vanquish Antica (UC)',
    [] = 'Subj.: Antican Praefectus (UC)',
    [] = 'Cure Status Ailments (UC)',
    [] = 'Staff Weapon Skills (UC)',
    [] = 'Conflict: Toraimarai Canal (UC)',
    [] = 'Vanquish Couerls (UC)',
    [] = 'Subjugation: Ose (UC)',
    [] = 'Heal Unity Allies (UC)',
    [] = 'Spoils (Dullahan Armor) (UC)',
    [] = 'Conflict: Outer Ra\'Kaznar (UC)',
    [] = 'Vanquish Dullahan (UC)',
    [] = 'Subj.: Capricious Cassie (UC)',
    [] = 'Magic Bursts (UC)',
    -- Unity (Wanted 1)
    [817] = 'Subjugation: Hugemaw Harold (UC)',
    [] = 'Subjugation: Bounding Belinda (UC)',
    [819] = 'Subjugation: Prickly Pitriv (UC)',
    [] = 'Subjugation: Ironhorn Baldurno (UC)',
    [] = 'Subjugation: Sleepy Mabel (UC)',
    [] = 'Subjugation: Valkurm Imperator (UC)',
    [] = 'Subjugation: Serpopard Ninlil (UC)',
    [] = 'Subjugation: Abyssdiver (UC)',
    [] = 'Subjugation: Intuila (UC)',
    [] = 'Subjugation: Emperor Arthro (UC)',
    [] = 'Subjugation: Orcfeltrap (UC)',
    [] = 'Subjugation: Lumber Jill (UC)',
    [] = 'Subjugation: Joyous Green (UC)',
    [] = 'Subjugation: Strix (UC)',
    [] = 'Subjugation: Warblade Beak (UC)',
    [] = 'Subjugation: Arke (UC)',
    [] = 'Subjugation: Largantua (UC)',
    [] = 'Subjugation: Beist (UC)',
    [] = 'Subjugation: Jester Malatrix (UC)',
    [] = 'Subjugation: Cactrot Veloz (UC)',
    [] = 'Subjugation: Woodland Mender (UC)',
    [854] = 'Subjugation: Sybaritic Samantha (UC)',
    [855] = 'Subj.: Keeper of Heiligtum (UC)',
    [856] = 'Subjugation: Douma Weapon (UC)',
    [857] = 'Subjugation: King Uropygid (UC)',
    [858] = 'Subjugation: Vedrfolnir (UC)',
    -- Unity (Wanted 2)
    [] = 'Subjugation: Immanibugard (UC)',
    [] = 'Subjugation: Tiyanak (UC)',
    [] = 'Subjugation: Muut (UC)',
    [] = 'Subjugation: Camahueto (UC)',
    [] = 'Subjugation: Voso (UC)',
    [] = 'Subjugation: Mephitas (UC)',
    [] = 'Subjugation: Coca (UC)',
    [] = 'Subjugation: Ayapec (UC)',
    [] = 'Subjugation: Specter Worm (UC)',
    [] = 'Subjugation: Azrael (UC)',
    [] = 'Subjugation: Borealis (UC)',
    [] = 'Subjugation: Garbage Gel (UC)',
    [] = 'Subjugation: Bakunawa (UC)',
    [] = 'Subjugation: Azure-tooth. Claw. (UC)',
    [] = 'Subjugation: Centurio XX-I (UC)',
    [] = 'Subjugation: Kub. Ja\'s Mhuufya (UC)',
    [] = 'Subjugation: Vidmapire (UC)',
    [] = 'Subjugation: Vermillion Fishfly (UC)',
    [] = 'Subjugation: Volatile Cluster (UC)',
    [] = 'Subjugation: Grand Grenade (UC)',
    [] = 'Subjugation: Sovereign Behem. (UC)',
    [] = 'Subjugation: Hidhaegg (UC)',
    [] = 'Subjugation: Tolba (UC)',
    [] = 'Subjugation: Carousing Celine (UC)',
    [] = 'Subjugation: Glazemane (UC)',
    [] = 'Subjugation: Bambrox (UC)',
    -- Unity (Wanted 3)
    [] = 'Subjugation: Thu\'ban (UC)',
    [] = 'Subjugation: Sarama (UC)',
    [] = 'Subjugation: Shedu (UC)',
    [] = 'Subjugation: Tumult Curator (UC)',
-- 'Vana\'versary'
    -- '15th Vana\'versary I'
    [] = 'Mythril Marathon',
    [] = 'Mythril Marathon (W)',
    [] = 'The Star of Tenshodo (W)',
    [] = 'Claret Carp (W)',
    [3363] = 'Gastro-revolution (W)', -- grape
    [] = 'Cure for What Ails You (W)',
    [] = 'Jinx (W)',
    [] = 'Stop Right There! (W)',
    [3367] = 'Signet, brb (W)',
    -- '15th Vana\'versary II'
    [] = 'Selbinary',
    [] = 'Selbinary (W)',
    [] = 'Mhauranian (W)',
    [] = 'Sunsand Rush (W)',
    [3371] = 'Gastro-revolution 2 (W)', -- apple pie
    [] = 'Crustacean Infusion (W)',
    [] = 'Yaaar! (W)',
    [3374] = 'Colorless (W)',
    [] = 'No Time to Be Sheepish (W)',
    -- '15th Vana\'versary III'
    [] = 'Papyrus Pursuer',
    [] = 'Papyrus Pursuer (W)',
    [] = 'Hide-and-Go-Seek (W)',
    [] = 'Full Deck (W)',
    [] = 'Unwavering Protector (W)',
    [3380] = 'Sit (W)',
    [3381] = 'Gastro-Revolution 3 (W)', -- roast mushroom
    [] = 'It\'s All a Blur (W)',
    [] = 'All That Glitters... (W)',
    -- '15th Vana\'versary IV'
    [] = 'Miratete 1',
    [] = 'Miratete 1 (W)',
    [] = 'Miratete 2 (W)',
    [] = 'A Strong Fellowship (W)',
    [] = 'Red Rover (W)',
    [] = '100 or Bust (W)',
    [] = 'Break the Blockade (W)',
    [3390] = 'Gastro-Revolution 4 (W)', -- ginger
    [] = 'Crustacean King (W)',
    -- '15th Vana\'versary V'
    [] = 'Say "Cheese"!',
    [] = 'Say "Cheese"! (W)',
    [3393] = 'Auction House Blues (W)',
    [] = 'Let Me Solo This (W)',
    [] = 'Ring Around the Rosie (W)',
    [] = 'The One True Path (W)',
    [] = '☆ (W)',
    [] = 'Gukumatz (W)',
    [] = 'See the Unseen (W)',
    -- '17th Vana\'versary'
    [] = '"True Love" Participation',
    [] = '"A Fond Farewell" Participation',
-- Other
    -- 'RoE Quests'
    [] = 'Telepoint Pilgrimage',
    [] = 'Culling the Darkness',
    [] = 'Petals of Recollection',
    [] = 'Grudge',
    [] = 'Golden Rule',
    [] = 'Impermanence',
    [] = 'Panta Rhei',
    [] = 'Leonine Excruciation',
    [] = 'Shiver Me Timbers',
    [] = 'Go With the Flow',
    [] = 'Over Ninety-Thousand',
    [] = 'Minnow Wrangler',
    [] = 'A Thousand Cuts',
    [] = 'Disappointment Valley',
    [] = 'Remembrance of Flowers Past',
    -- 'RoE Quests 2'
    [] = 'The Ygnas Directive 1',
    [] = 'The Ygnas Directive 2',
    [] = 'The Ygnas Directive 3',
    [] = 'The Ygnas Directive 4',
    [] = 'The Ygnas Directive 5',
    [] = 'The Ygnas Directive 6',
    [] = 'The Arciela Directive 1',
    -- 'RoE Quests 3'
    [] = 'Quell Your Rage',
    [965] = 'Temper Your Arrogance',
    [] = 'Stifle Your Envy',
    [] = 'Overcome your Cowardice',
    [] = 'Eliminate Your Apathy',
    [] = 'Filled to Capacity',
    [] = 'Over Capacity',
    [] = 'Way Over Capacity',
    -- 'Daily Objectives'
    [4082] = 'Vanquish Multiple Enemies (D)',
    [4083] = 'Buff Allies (D)',
    [4084] = 'Heal for 500+ HP (D)',
    -- 'Monthly Objectives'
        -- Pattern A
    [3779] = 'Gobbie Mystery Box (M)',
    [3782] = 'Chocobo Races (M)',
    [3785] = 'Walk of Echoes (M)',
        -- Pattern B
    [3780] = 'Grow and Harvest (M)',
    [3783] = 'Experience Chains (M)',
    [3786] = 'Wanted (M)',  -- the required mob changes I think
        -- Pattern C
    -- [3780] = 'Mog Garden Items (M)', -- wtf is going on???
    [3781] = 'Mog Garden Items (M)', -- 1/12/21 are there multiple ids for this?
    [3784] = 'Coalition Assignments (M)',
    [3787] = 'Delve (M)',
        -- Common
    [3788] = 'High-Tier Mission Battlefields (M)', -- it's the same id for all 3 patterns
}
--[[ ============================================== ]]
--[[ ============================================== ]]
--[[ ============================================== ]]